<?php

function disqus_migrate_help($path, $arg) {
  switch ($path) {
  case 'admin/settings/disqus/import':
    return '<p>'. t('The tool below allows you to import comments from <a href="@disqus">Disqus</a> to the  Drupal comment system.', array('@disqus' => 'http://disqus.com')) .'</p>';
  case 'admin/settings/disqus/export':
    return '<p>'. t('Clicking <em>"Export"</em> below will send the comments from the Drupal comment system to <a href="@disqus">Disqus</a>. Comments will only be exported once per forum, so you can click on "Export" as many times as you want and you will not get duplicates. Make sure to lengthen your PHP timeout time if you have many comments to export.', array('@disqus' => 'http://disqus.com')) .'</p>';
  }
}

/**
 * Implementation of hook_menu().
 */
function disqus_migrate_menu() {
  $items = array();
  $items['admin/settings/disqus/import'] = array(
    'title' => 'Import',
    'description' => 'Import comments from Disqus into the Drupal comment system.',
    'access arguments' => array('administer disqus'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('disqus_migrate_admin_settings_import'),
    'file' => 'disqus_migrate.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/disqus/export'] = array(
    'title' => 'Export',
    'description' => 'Export comments from the Drupal comment system to Disqus.',
    'access arguments' => array('administer disqus'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('disqus_migrate_admin_settings_export'),
    'file' => 'disqus_migrate.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
