<?php
/**
 * @file
 * List of translatable strings kept in info files.
 * All strings wrapped in t() to allow potx.module to extract them.
 */

function gmaps_dummy_potx_strings() {
  $list = array(
    //group titles
    t('Metric'),
    t('English'),
    t('Chinese units'),
    t('Japanese units'),
    t('Scientific'),
    t('Typographic units'),
    t('Obsolete units'),
    t('Comic/Everyday units'),

    //metric
    t('Meter'),
    t('Meters'),
    t('Yottameter'),
    t('Zettameter'),
    t('Exameter'),
    t('Petameter'),
    t('Terameter'),
    t('Gigameter'),
    t('Megameter'),
    t('Kilometer'),
    t('Hectometer'),
    t('Decameter'),
    t('Decimeter'),
    t('Centimeter'),
    t('Millimeter'),
    t('Micrometer'),
    t('Nanometer'),
    t('Picometer'),
    t('Femtometer'),
    t('Attometer'),
    t('Zeptometer'),
    t('Yoctometer'),

    //English
    t('Foot'),
    t('Feet'),
    t('Mil (Thou)'),
    t('Point'),
    t('Line'),
    t('Lines'),
    t('Pica'),
    t('Inch'),
    t('Hand'),
    t('Link'),
    t('Yard'),
    t('Fathom'),
    t('Fathoms'),
    t('Rod (Perch, Pole)'),
    t('Chain'),
    t("Ramsden's chain"),
    t("Ramsden's chains"),
    t('Cable'),
    t('Cables'),
    t('Furlong'),
    t('Furlongs'),
    t('Mile'),
    t('Nautical mile'),
    t('League'),
    t('Nautical league'),

    //Chinese
    t('lǐ'),
    t('yǐn'),
    t('zhàng'),
    t('bù'),
    t('chǐ'),
    t('cùn'),
    t('fēn'),
    t('lí'),
    t('háo'),
    t('sī'),
    t('hū'),

    //Japanese
    t('ri'),
    t('chō'),
    t('jō'),
    t('hiro'),
    t('ken'),
    t('shaku'),
    t('sun'),
    t('bu'),
    t('rin'),
    t('mō'),

    //Scientific
    t('Astronomical unit'),
    t('Light-year'),
    t('Parsec'),
    t('Ångström'),
    t('Bohr radius'),
    t('Planck length'),

    //Typographic
    t("European printer's point"),
    t('EU printer pt'),
    t("American printer's point"),
    t('US printer pt'),
    t('Desktop publishing point'),
    t('DTP pt'),
    t('PostScript point'),
    t('PS pt'),
    t('Didot point'),
    t('Didot pt'),

    //Obsolete
    t('Arabic nil-cubit'),
    t('black cubits'),
    t('Babylonian cubit'),
    t('cubits of Lagash'),
    t('Babylonian trade cubit'),
    t('Babylonian trade cubits'),
    t('Egyptian old royal cubit'),
    t('Egyptian old royal cubits'),
    t('Egyptian old trade cubit'),
    t('Egyptian old trade cubits'),
    t('Egyptian remen'),
    t('remen'),
    t('Egyptian royal cubit'),
    t('cubits'),
    t('Greek Kyrenaika cubit'),
    t('πεχυα'),
    t('Greek metrikos cubit'),
    t('πεχυα'),
    t('Guard cubit'),
    t('ammatu rabitu'),
    t('Hashimi cubit'),
    t('Hashimi cubits'),
    t('Jewish 1st Temple cubit'),
    t('Jewish 1st Temple cubits'),
    t('Jewish 2st Temple cubit'),
    t('Jewish 2st Temple cubits'),
    t('Jewish 2st Temple sacred cubit'),
    t('Jewish sacred cubits'),
    t('Mesopotamian nil-cubit'),
    t('nil-cubits'),
    t('Pergamon cubit'),
    t('Pergamon cubits'),
    t('Persian cubit'),
    t('Persian cubits'),
    t('Roman cubit'),
    t('cubitus'),
    t('Salamis cubit'),
    t('Salamis cubits'),
    t('Sumerian Nippur cubit'),
    t('nippur cubits'),
    t('Cana'),
    t('Canas'),
    t('Roman double-pace'),
    t('paces'),
    t('Russian verst'),
    t('верста'),
    t('California vara'),
    t('California varas'),
    t('Spanish vara'),
    t('Spanish varas'),
    t('Texas vara'),
    t('Texas varas'),
    t('vara chain'),
    t('vara chains'),

    //Comic
    t('American football field'),
    t('football fields'),
    t('Olympic swimming pool'),
    t('swimming pools'),
    t('Potrzebie'),
    t('Potrzebies'),
    t('Smoot'),
    t('Smoots'),
  );
}

?>
